/*
 * Copyright 2022 Red Hat, Inc. and/or its affiliates.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *       http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.kie.dar.compilationmanager.api.model;

/**
 * A generic <i>product</i> generated by specific engine
 */
public interface DARFinalOutput extends DARCompilationOutput {

    /**
     * Returns the <b>full resource identifier</b> to be invoked for execution
     * @return
     */
    String getFri();

    /**
     * Returns the type of model to be executed
     * @return
     */
    String getModelType();
}
